### ISSUE TITLE
custom domain pointed at outdated IP address

### ISSUE THREAD

**Issue by gkhullar** [astrosites/astrosites.github.io#2]
Hello! 

I am putting together a personal website, and have followed the steps laid out in the custom domain tab, and my website is being built as required without any major issues. A few hours after the custom domain (gouravkhullar.com) went live, I started receiving the following email from Github:

```
The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site.
```

I am wondering if this has to do with the IP addresses I added to the resource records under Google domains : 192.30.252.154 and 192.30.252.153, as mentioned in the link here: https://astrosites.github.io/custom-domain/? I am not quite sure what is needed to fix this. Any help would be appreciated :)

**Comment by stevenstetzler** [comment]
Thanks for using our resource.

I think our walk through is out-dated, and the warning is correct: the IP addresses 192.30.252.154 and 192.30.252.153 are outdated.

Referencing GitHub's documentation: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site (step 4), it looks like you should update the IP addresses to be:
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

These IP addresses are the "name servers" for GitHub. At the other end of those IP addresses are computers that know on GitHub's side where to route a request for your website at the domain name you picked.

I'll update our site right now to have the proper IP addresses. Let us know if this fix resolves things for you.

**Comment by gkhullar** [comment]
Hi Steven

Thanks for your prompt response here last month; this worked for me. 

A big thanks to you and Leah for creating a fantastic resource -- super easy to follow and implement.
